[package]
name = "project_euler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.10.0"
integer-sqrt = "0.1.5"
itertools = "0.12.1"
num-bigint = "0.4.4"
unfold = "0.2.0"
